// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfwwbggwrspyksridsea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmd3diZ2d3cnNweWtzcmlkc2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTI2NzgsImV4cCI6MjA2OTk2ODY3OH0.Fx4GwZCja4NcObj7QGrVFlcThu6WD0bTF2rgF9dhIIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});